<a href="https://colab.research.google.com/github/Emmahgithub/Analisis-Numerico-2025-1/blob/main/26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<font color="Teal" face="Comic Sans MS,arial">
  <h1 align="center"><i>Tarea 1 Analisis Numerico</i></h1>
  </font>
  <font color="Blue" face="Comic Sans MS,arial">
  <h5 align="center"><i>MARTINEZ ROSAS ZAYDE YAMILE</i></h5>
  <h5 align="center"><i>CAMACHO MARIN ANA KAREN</i></h5>
  <h5 align="center"><i>LÓPEZ AGUIRRE ROBERTO OCELOTZIN</i></h5>
  <h5 align="center"><i>VARGAS BAUTISTA EMMANUEL</i></h5>
  </font>

In [2]:
# Librerias
import numpy as np

In [8]:
def simetrica(A):
  """Verifica que la matriz A sea simétrica."""
  n = len(A)
  for i in range(n):
    for j in range(i, n):
      if A[i][j] != A[j][i]:
        return False
  return True

def cholesky_desc_LLt(A):

  """
  Realiza la factorización de Cholesky para una matriz A.
  La matriz A debe ser simétrica y definida positiva.

  Retorna la matriz triangular inferior L tal que A = L * L^T.
  """

  # Verifica que la matriz sea simétrica
  if not simetrica(A):
    raise ValueError("La matriz no es simétrica.")


  n = len(A) #Tamaño de la matriz
  L = [[0.0] * n for _ in range(n)] # L inicia como una matriz de ceros del tamaño que A

  # Itera sobre las columnas (y filas, por simetría) de A
  for j in range(n):
    # Suma de los cuadrados de los elementos anteriores en la fila j
    suma_cuadrados = 0.0
    for k in range(j):
      suma_cuadrados += L[j][k] ** 2

    # Calcula el valor diagonal de L
    diag = A[j][j] - suma_cuadrados
    if diag <= 0:
      raise ValueError("La matriz no es definida positiva.")
    L[j][j] = diag ** 0.5

    # Calcula los elementos debajo de la diagonal en la columna j
    for i in range(j + 1, n):
      suma_producto = 0.0
      for k in range(j):
        suma_producto += L[i][k] * L[j][k]
      L[i][j] = (A[i][j] - suma_producto) / L[j][j]
  return L

def cholesky_desc_LDLt(A):

  """
  Realiza la factorización de Cholesky para una matriz A.
  La matriz A debe ser simétrica y definida positiva.

  Retorna
  L, matriz triangular inferior
  D, lista que representa la diagonal de la matriz D
  tal que A = L * D * L^T.
  """

  # Verifica que la matriz sea simétrica
  if not simetrica(A):
    raise ValueError("La matriz debe ser simétrica.")

  n = len(A) # Tamaño de la matriz
  L = [[0.0] * n for _ in range(n)] # Inicializa L como matriz de ceros
  D = [0.0] * n # D como lista de ceros

  # Itera sobre cada columna j para calcular L y D
  for j in range(n):
    suma = 0.0
    # Calcula la suma de L[j][k]^2 * D[k] para k < j
    for k in range(j):
      suma += L[j][k] ** 2 * D[k]

    # Calcula el valor D[j][j]
    D[j] = A[j][j] - suma
    if D[j] <= 0:
      raise ValueError("La matriz no es definida positiva.")

    # Calcula los elementos L[i][j] para i > j
    for i in range(j + 1, n):
      suma_prod = 0.0
      for k in range(j):
        suma_prod += L[i][k] * L[j][k] * D[k]
      L[i][j] = (A[i][j] - suma_prod) / D[j]

    # Establece la diagonal de L en 1
    L[j][j] = 1.0

  return L, D

In [9]:
matrices = {
    "A": [
        [2, -1, 0],
        [-1, 2, -1],
        [0, -1, 2]
    ],
    "B": [
        [4, 1, 1, 1],
        [1, 3, -1, 1],
        [1, -1, 2, 0],
        [1, 1, 0, 2]
    ],
    "C": [
        [4, 1, -1, 0],
        [1, 3, -1, 0],
        [-1, -1, 5, 2],
        [0, 0, 2, 4]
    ],
    "D": [
        [6, 2, 1, -1],
        [2, 4, 1, 0],
        [1, 1, 4, -1],
        [-1, 0, -1, 3]
    ]
}

#a)

In [10]:
for name, M in matrices.items():
    L = np.array(cholesky_desc_LLt(M))
    A = np.array(M)
    print(f"\nMatriz {name}:")
    print("L =\n", L)
    print("Lᵗ =\n", L.T)
    print("¿L * Lᵗ ≈ A?:", np.allclose(L @ L.T, A))


Matriz A:
L =
 [[ 1.41421356  0.          0.        ]
 [-0.70710678  1.22474487  0.        ]
 [ 0.         -0.81649658  1.15470054]]
Lᵗ =
 [[ 1.41421356 -0.70710678  0.        ]
 [ 0.          1.22474487 -0.81649658]
 [ 0.          0.          1.15470054]]
¿L * Lᵗ ≈ A?: True

Matriz B:
L =
 [[ 2.          0.          0.          0.        ]
 [ 0.5         1.6583124   0.          0.        ]
 [ 0.5        -0.75377836  1.08711461  0.        ]
 [ 0.5         0.45226702  0.0836242   1.24034735]]
Lᵗ =
 [[ 2.          0.5         0.5         0.5       ]
 [ 0.          1.6583124  -0.75377836  0.45226702]
 [ 0.          0.          1.08711461  0.0836242 ]
 [ 0.          0.          0.          1.24034735]]
¿L * Lᵗ ≈ A?: True

Matriz C:
L =
 [[ 2.          0.          0.          0.        ]
 [ 0.5         1.6583124   0.          0.        ]
 [-0.5        -0.45226702  2.13200716  0.        ]
 [ 0.          0.          0.93808315  1.76635217]]
Lᵗ =
 [[ 2.          0.5        -0.5         0.    

#b)


In [11]:
for name, M in matrices.items():
    L, D = cholesky_desc_LDLt(M)
    L = np.array(L)
    D = np.diag(D)
    A = np.array(M)
    print(f"\nMatriz {name}:")
    print("L =\n", L)
    print("D =\n", D)
    print("Lᵗ =\n", L.T)
    print("¿L * D * Lᵗ ≈ A?:", np.allclose(L @ D @ L.T, A))


Matriz A:
L =
 [[ 1.          0.          0.        ]
 [-0.5         1.          0.        ]
 [ 0.         -0.66666667  1.        ]]
D =
 [[2.         0.         0.        ]
 [0.         1.5        0.        ]
 [0.         0.         1.33333333]]
Lᵗ =
 [[ 1.         -0.5         0.        ]
 [ 0.          1.         -0.66666667]
 [ 0.          0.          1.        ]]
¿L * D * Lᵗ ≈ A?: True

Matriz B:
L =
 [[ 1.          0.          0.          0.        ]
 [ 0.25        1.          0.          0.        ]
 [ 0.25       -0.45454545  1.          0.        ]
 [ 0.25        0.27272727  0.07692308  1.        ]]
D =
 [[4.         0.         0.         0.        ]
 [0.         2.75       0.         0.        ]
 [0.         0.         1.18181818 0.        ]
 [0.         0.         0.         1.53846154]]
Lᵗ =
 [[ 1.          0.25        0.25        0.25      ]
 [ 0.          1.         -0.45454545  0.27272727]
 [ 0.          0.          1.          0.07692308]
 [ 0.          0.          0.  